name: Close Pull Request

on:
  pull_request_target:
    types: [opened]
    branches:
    - master
    
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        # Optional. Post a issue comment just before closing a pull request.
        comment: "We do not accept PRs on the master branch. Please submit your PR through the dev or beta branch instead of the master one, thanks. If you have any questions, please feel free to contact us."
