name: UnPublish

on: 
  workflow_dispatch:
    inputs:
      version:
        description: '1.0.0-rc.1'
        required: true
        default: '1.0.0-rc.1'

jobs:

  unpublish:
    runs-on: ubuntu-latest
    steps:
      - run: npm unpublish homebridge-eufy-security@${{ github.event.inputs.version }} --force
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
